<?php

// Sample data represents the json api data decoded into an associative array

$events_data = array(
    array('created' => 1477489288000,
    'duration' => 4500000,
    'id' => 'mxjfdmywcbgb',
    'name' => "Let's get out and get moving!",
    'rsvp_limit' => 20,
    'status' => 'upcoming',
    'time' => 1483552800000,
    'updated' => 1477489288000,
    'utc_offset' => -25200000,
    'waitlist_count' => 0,
    'yes_rsvp_count' => 4,
    'venue' => array('id' => 247239,
                'name' => "Dawson Park",
                'lat' => 40.190284729004,
                'lon' => -105.13925170898,
                'repinned' => '',
                'address_1' => "1757 Harvard St",
                'city' => "Longmont",
                'country' => "us",
                'localized_country_name' => "USA",
                'zip' => 80503,
                'state' => "CO"),
    'group' => array('created' => 1428507043000,
                'name' => "Front Range Mind & Body Fitness",
                'id' => 18538621,
                'join_mode' => "open",
                'lat' => 40.169998168945,
                'lon' => -105.12999725342,
                'urlname' => "Front-Range-Mind-Body-Fitness-Meetup",
                'who' => "Movers and shakers"),
    'link' => "https://www.meetup.com/Front-Range-Mind-Body-Fitness-Meetup/events/236488997/",
    'description' => "<p>Walking is the super food of movement, but like any super food the way you consume it matters.  On our walk we will discuss some of the junk foods of walking and we will play around with how we walk.</p> <p>Meet at the Dawson park playground in Longmont, Colorado for a walk around McIntosh lake 3 1/2 miles. As we walk we will discuss, gait and different ways of walking/running. What's natural, what's not. It's fun and beautiful and a great way to get to know each other.</p>",
    'visibility' => "public"),
    
    array('created' => 1479273350000,
    'duration' => 5400000,
    'id' => "hpgmhlywcbgb",
    'name' => "Annual Gift Exchange!",
    'rsvp_limit' => 25,
    'status' => "upcoming",
    'time' => 1483553700000,
    'updated' => 1479355969000,
    'utc_offset' => -25200000,
    'waitlist_count' => 0,
    'yes_rsvp_count' => 13,
    'group' => array('created' => 1301536727000,
                'name' => "Boulder Business Women's Connection",
                'id' => 1807425,
                'join_mode' => "open",
                'lat' => 40.040000915527,
                'lon' => -105.30999755859,
                'urlname' => "Boulder-Business-Womens-Connection",
                'who' => "Members"),
    'link' => "https://www.meetup.com/Boulder-Business-Womens-Connection/events/235615274/",
    'manual_attendance_count' => 0,
    'description' => "<p>The first Wednesday in January is traditionally our annual gift exchange for <b>Regular meeting attendees</b>. Because we don't conduct any business that day and the meeting is a holiday party, it is <b>open only to members who attend regularly on Wednesdays</b>. Don't forget to bring a wrapped and unmarked gift valued at approximately $25 for the gift exchange. Please, no White Elephants! This should be a gift you would be excited to receive yourself. Fun times!</p>",
    'visibility' => "public"),

    array('created' => 1360872073000,
    'duration' => 6300000,
    'fee' => array('accepts' => "cash",
              'amount' => 13,
              'currency' => "USD",
              'description' => "per person",
              'label' => "Price",
              'required' => ''),
    'id' => 236528121,
    'name' => "Business Lunch",
    'rsvp_limit' => 30,
    'status' => "upcoming",
    'time' => 1483553700000,
    'updated' => 1367338481000,
    'utc_offset' => -25200000,
    'waitlist_count' => 0,
    'yes_rsvp_count' => 3,
    'group' => array('created' => 1359923978000,
                'name' => "Longmont Womens Networking",
                'id' => 7010192,
                'join_mode' => "approval",
                'lat' => 40.169998168945,
                'lon' => -105.12999725342,
                'urlname' => "Longmont-Womens-Networking",
                'who' => "Dynamite Women"),
    'link' => "https://www.meetup.com/Longmont-Womens-Networking/events/236528121/",
    'description' => "<p>We meet Weekly, Please come prepared with plenty of business cards to pass, two 33 second commercial/ elevator moments. we have chosen to support le peep for allowing us to use the space, the 13.00 per week fee covers the room, any lunch item off the menu, tax and gratuity. They have great food and drink options and many gluten free accommodations if that is better for you.</p>",
    'visibility' => "public")
);




$groups_data = array(
    'score' => 1,
    'id' => 2347761,
    'name' => "Women's Development Council (WDC)",
    'link' => "https://www.meetup.com/womensdevelopmentcouncil/",
    'urlname' => "womensdevelopmentcouncil",
    'description' => "<p>Develop, organize and promote activities that educate, encourage, support and enhance the development of women in business. * WDC's primary focus is connecting Colorado business women's networking groups to maximize networking opportunities through coordinated events. * WDC supports women's networking groups in Fort Collins, Greeley, Loveland, Firestone and Windsor with program development, marketing and event support.</p>
<p>Join us on Facebook&nbsp;</p>
<p><a href='https://www.facebook.com/pages/WDC-Womens-Development-Council/197352480307639' class='linkified'>https://www.facebook.com/pages/WDC-Womens-Development-Council</a></p>",
    'created' => 1313472252000,
    'city' => "Greeley",
    'country' => "US",
    'localized_country_name' => "USA",
    'state' => "CO",
    'join_mode' => "open",
    'visibility' => "public",
    'lat' => 40.41,
    'lon' => -104.76,
    'members' => 488,
    'organizer' => array( 'id' => 26790202,
                          'name' => "Jennifer McRae",
                          'bio' => "I began my career in travel in 1988 after receiving a degree in Travel. Opening Crown Travel & Events in 2010, I specialize in All-Inclusives, Cruises & Tours; along with  family reunions & groups. I am on the board for Women's Development Council.",
                          'photo' => array(
                              'id' => 189835512,
                              'highres_link' => "http://photos2.meetupstatic.com/photos/member/d/8/d/8/highres_189835512.jpeg",
                              'photo_link' => "http://photos2.meetupstatic.com/photos/member/d/8/d/8/member_189835512.jpeg",
                              'thumb_link' => "http://photos2.meetupstatic.com/photos/member/d/8/d/8/thumb_189835512.jpeg",
                              'type' => "member",
                              'base_url' => "http://photos2.meetupstatic.com")),
    'who' => "Entrepreneurs",
    'group_photo' => array( 'id' => 48658471,
                            'highres_link' => "http://photos3.meetupstatic.com/photos/event/e/4/6/7/highres_48658471.jpeg",
                            'photo_link' => "http://photos3.meetupstatic.com/photos/event/e/4/6/7/600_48658471.jpeg",
                            'thumb_link' => "http://photos3.meetupstatic.com/photos/event/e/4/6/7/thumb_48658471.jpeg",
                            'type' => "event",
                            'base_url' => "http://photos3.meetupstatic.com"),
    'timezone' => "US/Mountain",
    'next_event' => array('id' => "qtsndlywcbfb",
                          'name' => "BWNFC MONTHLY MEETING: RSVP at WWW.BWNFC.ORG",
                          'yes_rsvp_count' => 7,
                          'time' => 1483467300000,
                          'utc_offset' => -25200000),
    'category' => array('id' => 2,
                        'name' => "Career & Business",
                        'shortname' => "Business",
                        'sort_name' => "Career & Business"),
    'photos' => array(
            array('id' => 244113142,
                  'highres_link' => "http://photos4.meetupstatic.com/photos/event/8/1/7/6/highres_244113142.jpeg",
                  'photo_link' => "http://photos4.meetupstatic.com/photos/event/8/1/7/6/600_244113142.jpeg",
                  'thumb_link' => "http://photos4.meetupstatic.com/photos/event/8/1/7/6/thumb_244113142.jpeg",
                  'type' => "event",
                  'base_url' => "http://photos4.meetupstatic.com"),
            array('id' => 392091242,
                  'highres_link' => "http://photos2.meetupstatic.com/photos/event/c/8/2/a/highres_392091242.jpeg",
                  'photo_link' => "http://photos4.meetupstatic.com/photos/event/c/8/2/a/600_392091242.jpeg",
                  'thumb_link' => "http://photos2.meetupstatic.com/photos/event/c/8/2/a/thumb_392091242.jpeg",
                  'type' => "event",
                  'base_url' => "http://photos4.meetupstatic.com"),
            array('id' => 411384542,
                  'highres_link' => "http://photos2.meetupstatic.com/photos/event/5/f/d/e/highres_411384542.jpeg",
                  'photo_link' => "http://photos2.meetupstatic.com/photos/event/5/f/d/e/600_411384542.jpeg",
                  'thumb_link' => "http://photos2.meetupstatic.com/photos/event/5/f/d/e/thumb_411384542.jpeg",
                  'type' => "event",
                  'base_url' => "http://photos2.meetupstatic.com"),
            array('id' => 435325375,
                  'highres_link' => "http://photos3.meetupstatic.com/photos/event/6/3/1/f/highres_435325375.jpeg",
                  'photo_link' => "http://photos3.meetupstatic.com/photos/event/6/3/1/f/600_435325375.jpeg",
                  'thumb_link' => "http://photos3.meetupstatic.com/photos/event/6/3/1/f/thumb_435325375.jpeg",
                  'type' => "event",
                  'base_url' => "http://photos3.meetupstatic.com"))
);

?>